// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5NR--KQWxdEAmoQ2zopUDA9ewsvmQbOM',
    appId: '1:249399801748:web:ee92e4f2ce5e7752c50181',
    messagingSenderId: '249399801748',
    projectId: 'notes-2737e',
    authDomain: 'notes-2737e.firebaseapp.com',
    databaseURL: 'https://notes-2737e-default-rtdb.firebaseio.com',
    storageBucket: 'notes-2737e.firebasestorage.app',
    measurementId: 'G-CNLN3BZVL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq3cjZSxaSsRQrh2X9n1L7yHWlcpeLcqw',
    appId: '1:249399801748:android:0f92a2e88524be42c50181',
    messagingSenderId: '249399801748',
    projectId: 'notes-2737e',
    databaseURL: 'https://notes-2737e-default-rtdb.firebaseio.com',
    storageBucket: 'notes-2737e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV2cE9Ars7p1zdyrwzFI1tml2JFBkq_Zc',
    appId: '1:249399801748:ios:3559d20a738fbc6fc50181',
    messagingSenderId: '249399801748',
    projectId: 'notes-2737e',
    databaseURL: 'https://notes-2737e-default-rtdb.firebaseio.com',
    storageBucket: 'notes-2737e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV2cE9Ars7p1zdyrwzFI1tml2JFBkq_Zc',
    appId: '1:249399801748:ios:3559d20a738fbc6fc50181',
    messagingSenderId: '249399801748',
    projectId: 'notes-2737e',
    databaseURL: 'https://notes-2737e-default-rtdb.firebaseio.com',
    storageBucket: 'notes-2737e.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5NR--KQWxdEAmoQ2zopUDA9ewsvmQbOM',
    appId: '1:249399801748:web:527c2e4ecd9d4ca0c50181',
    messagingSenderId: '249399801748',
    projectId: 'notes-2737e',
    authDomain: 'notes-2737e.firebaseapp.com',
    databaseURL: 'https://notes-2737e-default-rtdb.firebaseio.com',
    storageBucket: 'notes-2737e.firebasestorage.app',
    measurementId: 'G-R9SL4SLHXX',
  );
}
